### ISSUE TITLE
water not being changed

### ISSUE THREAD

**Issue by RobertRR11** [ewanhowell5195/resourcePackConverter#5]
When trying to downgrade a pack to 1.12 or below, the water is not being colored blue and will show up white ingame. Probably also happens when upgrading over 1.12, but I haven't tested that.

**Comment by ewanhowell5195** [comment]
this is due to the fact that in older versions of the game, the water didnt follow a colormap, and instead was just coloured blue in the texture. You will have to fix this manually.

I plan to attempt to fix this in the converter in the future, but idk how well it will work.
Converting from 1.12 to 13 is easier as you just grayscale the texture.
